name = "vkomari-cf"
main = "src/index.js"
compatibility_date = "2025-06-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vkomari-db"
migrations_dir = "./migrations"
